# Generated by Django 3.0.7 on 2020-06-11 03:15

from django.db import migrations, models
import questions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Number', models.IntegerField()),
                ('Question_Text', models.TextField(blank=True, null=True)),
                ('Question_Image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('Question_Answer', models.CharField(max_length=50, validators=[questions.models.lowercase_answer])),
            ],
        ),
    ]
