# Generated by Django 3.1 on 2020-08-26 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_ans_time',
            field=models.TimeField(default=datetime.datetime(2020, 8, 27, 16, 0)),
        ),
    ]
