# Generated by Django 3.0.7 on 2020-06-12 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_ans_time',
            field=models.TimeField(default=datetime.datetime(2020, 6, 13, 16, 0)),
        ),
    ]
