# Generated by Django 3.0.8 on 2020-08-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_last_ans_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_que',
            field=models.IntegerField(default=-3),
        ),
    ]
